# Generated by Django 5.2.6 on 2025-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address'), ('office', 'Office Address'), ('other', 'Other')], default='shipping', max_length=20),
        ),
    ]
