# Generated by Django 5.2.6 on 2025-09-06 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Category Name (English)')),
                ('name_it', models.CharField(max_length=100, unique=True, verbose_name='Category Name (Italian)')),
                ('name_de', models.CharField(max_length=100, unique=True, verbose_name='Category Name (German)')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Sub-Category Name (English)')),
                ('name_it', models.CharField(max_length=100, unique=True, verbose_name='Sub-Category Name (Italian)')),
                ('name_de', models.CharField(max_length=100, unique=True, verbose_name='Sub-Category Name (German)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Product Sub-Category',
                'verbose_name_plural': 'Product Sub-Categories',
                'ordering': ['category__name_en', 'name_en'],
                'unique_together': {('category', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Product Name (English)')),
                ('name_it', models.CharField(max_length=255, verbose_name='Product Name (Italian)')),
                ('name_de', models.CharField(max_length=255, verbose_name='Product Name (German)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_it', models.TextField(blank=True, verbose_name='Description (Italian)')),
                ('description_de', models.TextField(blank=True, verbose_name='Description (German)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Stock Keeping Unit')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_reviews', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsubcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (English)')),
                ('alt_text_it', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (Italian)')),
                ('alt_text_de', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (German)')),
                ('is_main', models.BooleanField(default=False, help_text='Set as the main display image for the product.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_main', 'id'],
                'unique_together': {('product', 'is_main')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('color_en', models.CharField(max_length=50, verbose_name='Color (English)')),
                ('color_it', models.CharField(max_length=50, verbose_name='Color (Italian)')),
                ('color_de', models.CharField(max_length=50, verbose_name='Color (German)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('SKU_variant', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Variant SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['size', 'color_en'],
                'unique_together': {('product', 'size', 'color_en')},
            },
        ),
    ]
