# Generated by Django 5.2.6 on 2025-09-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('running_shoes', 'Running Shoes'), ('cycling_shoes', 'Cycling Shoes'), ('hockey_shoes', 'Hockey Shoes'), ('ski_boots', 'Ski Boots'), ('basketball_shoes', 'Basketball Shoes'), ('golf_shoes', 'Golf Shoes'), ('football_shoes', 'Football Shoes'), ('tennis_shoes', 'Tennis Shoes'), ('climbing_shoes', 'Climbing Shoes'), ('casual_sneaker', 'Casual Sneakers'), ('dress_shoes', 'Dress Shoes'), ('comfortable_shoes', 'Comfortable Shoes'), ('sandals', 'Sandals'), ('work_shoes', 'Work Shoes'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('name_en', models.CharField(max_length=200)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('name_it', models.CharField(blank=True, max_length=200, null=True)),
                ('description_it', models.TextField(blank=True, null=True)),
                ('name_de', models.CharField(blank=True, max_length=200, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
